language: java
sudo: false

jdk:
  - oraclejdk8

branches:
  only:
  - master

script:
  - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  - mvn compile -B
  - mvn test
  - mvn package